version: '3'
services:
    apache:
        build: .docker/apache
        container_name: movie-manager_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/movie-manager
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: movie-manager_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root8root
            MYSQL_DATABASE: movie-manager
            MYSQL_USER: root
            MYSQL_PASSWORD: root8root

    php:
        build: .docker/php
        container_name: movie-manager_php
        volumes:
          - .:/home/wwwroot/movie-manager
        environment:
          - maildev_host=movie-manager_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: movie-manager_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: movie-manager_maildev
        ports:
          - 8001:80