# prefix: /api/

getFilmByImdbID:
    path: /movies/imdbID/{imdbID}
    controller: App\Controller\Api\MovieListController::getOneByImdbID

getFilmById:
    path: /movies/id/{id}
    controller: App\Controller\Api\MovieListController::getOneById

apiListMovie:
    path: /movies/
    controller: App\Controller\Api\MovieListController::index