# prefix: /api/

getFilmByImdbID:
    path: /movies/imdbID/{imdbID}
    controller: App\Controller\Api\MovieListController::getOneByImdbID

getFilmById:
    path: /movies/id/{id}
    controller: App\Controller\Api\MovieListController::getOneById

apiListMovie:
    path: /movies/
    controller: App\Controller\Api\MovieListController::index

apiListMovieToSee:
    path: /movies/toSee
    controller: App\Controller\Api\MovieListController::toSee

apiListMovieSee:
    path: /movies/see
    controller: App\Controller\Api\MovieListController::see

apiLastMovieToSeeAndSee:
    path: /movies/last
    controller: App\Controller\Api\MovieListController::lastToSeeAndSee

apiEditToSeeStatus: 
    path: /movies/toSee/{imdbID}
    controller: App\Controller\Api\MovieListController::editToSeeStatus

apiEditSeeStatus: 
    path: /movies/see/{imdbID}
    controller: App\Controller\Api\MovieListController::editSeeStatus

apiSetMovieToSeeSeen:
    path: /movies/toSee/{imdbID}/seen
    controller: App\Controller\Api\MovieListController::setSeen

apiSeeAgain:
    path: /movies/see/{imdbID}/seeAgain
    controller: App\Controller\Api\MovieListController::seeAgain

apiSearch: 
    path: /movies/search/{search}
    controller: App\Controller\Api\MovieListController::search

apiSearchWithPage: 
    path: /movies/search/{search}/{page}
    controller: App\Controller\Api\MovieListController::search

apiAddMovieToSee: 
    path: /movies/toSee/{imdbID}/add
    controller: App\Controller\Api\MovieListController::seeAgain

apiAddMovieSee: 
    path: /movies/see/{imdbID}/add
    controller: App\Controller\Api\MovieListController::seen