home:
    path: /
    controller: App\Controller\MovieController::listMovies

multiplePage:
    path: ./routes/multiplePageRoutes.yaml

app:
    path: /app/{reactRouting}
    defaults: { _controller: App\Controller\AppController::index, reactRouting: null }
    requirements:
        reactRouting: ".+"

apiRouting: 
    resource: ./routes/apiRoutes.yaml
    prefix: /api/