home:
    path: /
    controller: App\Controller\MovieController::listMovies

multiplePage:
    path: ./routes/multiplePageRoutes.yaml

app:
    path: /app/
    controller: App\Controller\AppController::index

apiRouting: 
    resource: ./routes/apiRoutes.yaml
    prefix: /api/