home:
    path: /
    controller: App\Controller\MovieController::listMovies

multiplePage:
    path: ./routes/multiplePageRoutes.yaml

apiRouting: 
    resource: ./routes/apiRoutes.yaml
    prefix: /api/