listMovie:
    path: /list/movies/
    controller: App\Controller\MovieController::listMovies

apiListMovie:
    path: /api/movies/
    controller: App\Controller\MovieController::apiListMovies

getFilmByImdbID:
    path: /api/getFilmByImdbID
    controller: App\Controller\MovieController::getFilmByImdbID
